# secrets.conf — НЕ загружать в будущем в Git и держать приватно, эти строки для примера
ADMIN_PASSWORD=MyStrongAdmin123
DATABASE_PASSWORD=MyDBPass456
RABBIT_PASSWORD=RabbitSecret789
SERVICE_PASSWORD=ServicePass000
HOST_IP=127.0.0.1
